name: Create Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Wrapper
        run: |
          gradle wrapper --gradle-version 8.7

      - name: Save files
        uses: actions/upload-artifact@v4
        with:
          name: wrapper-files
          path: |
            gradlew
            gradlew.bat
            gradle/wrapper/
